name: base
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  #  - "cudatoolkit>=11.6.0"
  #  - cudnn
  #  - "pytorch=*=*cuda*"
  #  - numba
  - dask>=2023.5.0
  - distributed>=2023.5.0
  - fsspec>=2023.5.0
  - gdal>=3.6.4
  - geopandas>=0.13.0
  - netcdf4>=1.6.3
  - numpy>=1.24.3
  - pandas>=2.0
  - scipy>=1.10.1
  - xarray>=2023.5.0
  - nb_conda_kernels
  - matplotlib
  - python=3.9.16
  - jupyter_client
  - nb_conda_kernels
  - ipympl
  - ipyleaflet

    #  - "tensorflow-gpu>=2.11.0"
    #  - tensorboard 

