name: base
channels: 
  - conda-forge
  - defaults
dependencies:
  - "requests-toolbelt>=1.0.0"
  - "h5py>=3.13.0"
  - "graphviz>=12.2.1"
  - "basemap-data-hires>=1.3.2"
  - "numexpr>=2.10.2"
  - "requests-oauthlib>=2.0.0"
  - "ogh>=0.2.1"
  - "openblas>=0.3.29"
  - "dill>=0.3.5.1"
  - "rasterstats>=0.20.0"
  - "scikit-image>=0.25.2"
  - "sympy>=1.13.3"
  - "pygmt>=0.14.2"
  - "geemap>=0.35.2"
  - "hvplot>=0.11.2"
  - "xesmf>=0.8.8"
  - "ipympl>=0.9.6"
##  - "ulmo>=0.8.8" Removed until https://github.com/ulmo-dev/ulmo/issues/215 is resolved
