name: base
channels: 
  - conda-forge
  - defaults
dependencies:
  - "basemap-data-hires>=1.3.2"
  - "beautifulsoup4>=4.11.1"
  - "bokeh>=2.4.3"
  - "dask>=2022.8.0"
  - "dill>=0.3.5.1"
  - "descartes>=1.1.0"
  - "distributed>=2022.8.0"
  - "fiona>=1.8.21"
  - "folium>=0.12.1"
  - "fsspec>=2022.7.1"
  - "gdal>=3.5.0"
  - "geemap>=0.16.2"
  - "geopandas>=0.11.1"
  - "graphviz>=5.0.0"
  - "h5py>=3.7.0"
  - "ipyleaflet>=0.17.0"
  - "landlab>=2.5.0"
  - "matplotlib>=3.5.2"
  - "netcdf4>=1.6.0"
  - "networkx>=2.8.5"
  - "numpy>=1.23.1"
  - "numexpr>=2.8.3"
  - "ogh>=0.2.1"
  - "openblas>=0.3.20"
  - "pandas>=1.4.3"
  - "patsy>=0.5.2"
  - "pyproj>=3.3.1"
  - "pyshp>=2.1.3"
  - "pygmt>=0.7.0"
  - "python-wget>=3.2"
  - "rasterio>=1.3.0"
  - "rasterstats>=0.17.0"
  - "requests>=2.27.1"
  - "requests-oauthlib>=1.3.1"
  - "requests-toolbelt>=0.9.1"
  - "scikit-image>=0.19.3"
  - "scikit-learn>=1.1.2"
  - "scipy>=1.9.0"
  - "seaborn>=0.11.2"
  - "shapely>=1.8.2"
  - "statsmodels>=0.13.2"
  - "suds-jurko>=0.6"
  - "sympy>=1.10.1"
  - "tqdm>=4.62.3"
  - "ulmo>=0.8.8"
  - "xarray>=2022.6.0"
