ARG BASE_VERSION

# derived from the minimal singleuser image 
FROM cuahsi/singleuser-base:$BASE_VERSION

MAINTAINER Tony Castronova <acastronova@cuahsi.org>

USER $NB_UID

# set the home dir
ENV HOME=/home/$NB_USER/data

# set the default terminal start path to $HOME
RUN echo 'cd $HOME' >> .profile

# remove work dir b/c we're using "data"
RUN rm -rf ~/work

USER jovyan
