#!/usr/bin/env python3


"""
Purpose: This script executes ESMF regridding operations using Docker.
Requirements: Docker installed on system, python-docker, python 3.8+

Author: Tony Castronova <acastronova@cuahsi.org>
Date: 07.12.2022
Org: CUAHSI
"""

import os
import sys
import docker
import argparse
from pathlib import Path
from typing import Union


def get_docker_client_with_fallback():
    try:
        return docker.from_env()
    except docker.errors.DockerException:
        # Try macOS-specific path
        macos_socket = f"unix:///Users/{os.getlogin()}/.docker/run/docker.sock"
        if os.path.exists(macos_socket.replace("unix://", "")):
            return docker.DockerClient(base_url=macos_socket)
        raise  # Re-raise the original exception if no fallback found


def _check_image_exists(img: str) -> bool:
    client = get_docker_client_with_fallback()
    installed_images = client.images.list()
    for installed_image in installed_images:
        if len(installed_image.tags) > 0:  # make sure that a tag exists
            if img == installed_image.tags[0]:
                return True
    return False


def _pull_image(img: str) -> bool:
    client = get_docker_client_with_fallback()
    try:
        print(img)
        client.images.pull(img)
    except docker.errors.APIError as e:
        print(f"\nError encounter while pulling {img}")
        print(f'{"-"*25}\n{e}\n{"-"*25}')
        return False
    return True


def execute_regrid(
    image: str,
    method: str,
    interp: str,
    forcing_path: Union[str, Path],
    geogrid_path: Union[str, Path],
    format: str,
    output_path: Union[str, Path, None] = None,
    verbose: bool = False,
) -> bool:

    # define and clean the file paths needed for regridding
    forcing_path = Path(forcing_path)
    geogrid_path = Path(geogrid_path)

    # define required volume mounts
    mnt = {
        f"{geogrid_path.absolute()}": {
            "bind": f"/home/{geogrid_path.name}",
            "mode": "rw",
        },
        f"{forcing_path.absolute()}/": {"bind": "/home/input_files", "mode": "rw"},
    }

    if output_path is not None:
        output_path = Path(output_path)
        # add optional volume mount
        mnt[f"{output_path.absolute()}"] = {"bind": "/home/output_files", "mode": "rw"}

    # define the execution command
    cmd = f"-f /home/input_files -g /home/{geogrid_path.name} -m {method} -i {interp} -F {format}"

    # add verbosity flag
    if verbose:
        cmd += " -v"

    client = get_docker_client_with_fallback()

    try:

        container = client.containers.run(
            image, cmd, volumes=mnt, auto_remove=True, detach=True, stream=True
        )

        # print stdout if verbose is True. If not, looping over
        # logs makes the program wait for the container to exit
        # which is what we want anyway.
        for line in container.logs(stream=True, follow=True):
            if verbose:
                print(line.decode(), end="", flush=True)

    except docker.errors.APIError as e:
        print(f"Error encountered while executing regridding operation: \n\t {e}")
        return False

    if format == "NETCDF":
        # rename output files to match WRF-Hydro's expected naming convention
        if output_path is not None:
            rename_nc_output_files(output_path)

    return True


def rename_nc_output_files(output_path: Union[str, Path]) -> None:
    """
    Rename output files generated by the NetCDF regridding operation
    to match WRF-Hydro's expected naming convention.
    """
    output_path = Path(output_path)
    for file in output_path.glob("*.nc"):
        parts = file.name.split(".")
        new_name = f"{parts[1][1:]}{parts[2][:2]}.LDASIN_DOMAIN1"
        file.rename(output_path / new_name)
        print(f"Renamed {file.name} to {new_name}")


if __name__ == "__main__":

    # argparse
    parser = argparse.ArgumentParser()

    # required args
    parser.add_argument(
        "-f", "--forcing-path", required=True, help="path containing raw forcing files"
    )
    parser.add_argument(
        "-g",
        "--geogrid-path",
        required=True,
        help="path to geogrid file that will be used for regridding",
    )
    parser.add_argument(
        "-o",
        "--output-path",
        required=True,
        help="path to save output files",
    )

    # optional args
    parser.add_argument(
        "-F",
        "--forcing-format",
        default="GRIB",
        help="the format of the input forcing data, GRIB or NETCDF (default=GRIB)",
        choices=["GRIB", "NETCDF"],
    )
    parser.add_argument(
        "-i",
        "--image-version",
        default="0.2",
        help="Version of the cuahsi/wrf-hydro-regrid image to use, default=0.2",
    )
    parser.add_argument(
        "-m",
        "--method",
        help="regridding method to be used, default=NLDAS",
        choices=["NLDAS"],
        default="NLDAS",
    )
    parser.add_argument(
        "--interp",
        default="bilinear",
        help="regridding interpolation method to use, default=bilinear",
        choices=["conserve", "bilinear"],
    )
    parser.add_argument(
        "-v",
        "--verbose",
        default=False,
        action="store_true",
        help="flag to enable verbose output",
    )

    args = parser.parse_args()

    image = f"cuahsi/wrfhydro-regrid:{args.image_version}"

    # print user supplied arguments/parameters
    print(
        f"""
    ----------------------------------------------------
    Executing WRFHydro-Regrid with the following Options
    ----------------------------------------------------
       Docker Image:  {image}
       Input Format:  {args.forcing_format}
       Regrid Method: {args.method}
       Interp Method: {args.interp}
       Output Path:   {args.output_path}
       Forcing Path:  {args.forcing_path}
       Geogrid Path:  {args.geogrid_path}
    ----------------------------------------------------
    """
    )

    # checking the user supplied paths for errors
    print("Checking user supplied paths for errors...")
    errors = []
    for input_val in [args.forcing_path, args.geogrid_path, args.output_path]:
        input_path = Path(input_val)
        if not input_path.exists():
            errors.append(f"ERROR: Path does not exist {input_path.absolute()}")
    if len(errors) > 0:
        for e in errors:
            print(e)
        sys.exit(1)

    # check if image exists on system
    print("Checking if Docker image exists...")
    img_exists = _check_image_exists(image)
    print(f'Image "{image}" exists: {img_exists}')

    # pull image
    if not img_exists:
        print(f"Attempting to pull image: {image}")
        pull_success = _pull_image(image)
        if not pull_success:
            sys.exit(1)

    # execute regridding operations
    print("Begin Regridding Operations...")
    success = execute_regrid(
        image,
        args.method,
        args.interp,
        args.forcing_path,
        args.geogrid_path,
        args.forcing_format,
        args.output_path,
        args.verbose,
    )
