# get the base image version as a build arg
ARG VERSION

FROM pangeo/pangeo-notebook-onbuild:$VERSION

MAINTAINER Tony Castronova <acastronova@cuahsi.org>

USER root

# install system libs
RUN apt-get update && apt-get install -y --no-install-recommends \
git \
vim \
#ca-certificates \
#build-essential \
#gnupg \ 
#wget \
#libgdal-dev \
#libmpich-dev \
#sudo \
&& rm -rf /var/lib/apt/lists/*

## install icommands
#RUN wget -qO - https://packages.irods.org/irods-signing-key.asc | sudo apt-key add - \
#&& echo "deb [arch=amd64] https://packages.irods.org/apt/ xenial main" | sudo tee /etc/apt/sources.list.d/renci-irods.list  \
#&& apt-get update \
#&& apt-get install -y irods-icommands

## install TauDEM
#ARG TAG=v5.3.7
#RUN git clone --branch $TAG https://github.com/dtarb/TauDEM.git /tmp/TauDEM \
#&& cd /tmp/TauDEM/src \
#&& sed -i 's#\.\.#/usr/local/bin#g' makefile \
#&& make \
#&& rm -rf /tmp/*
#
#RUN pip install hs_restclient hstools

USER jovyan

RUN rm -rf ~/work
