name: base
channels:
  - conda-forge
dependencies:
  - fiona>=1.8.22
  - geopandas>=0.12.2
  - numba>=0.56.4
  - numpy>=1.23.5
  - pandas>=2.0.0
  - rasterio>=1.3.6
  - rasterstats>=0.18.0
  - richdem>=0.3.4
  - tqdm>=4.65.0
  - seaborn>=0.12.2
  - python-dotenv>=1.0.0
  - natsort>=8.3.1
  - memory_profiler>=0.61.0
  - xarray>=2023.1.0
  - netcdf4>=1.6.3
  - pytables>=3.8.0
  - pyproj>=3.5.0
  - psycopg2-binary==2.9.3
  - boto3>=1.26.76
  - pytest>=7.3.0
  - whitebox>=2.3.1
  - whitebox_tools
  - shapely>=2.0.1
  - pyarrow>=11.0.0
  - rtree>=1.0.1
  - py7zr>=0.20.4
  - scipy>=1.10.1
  - python==3.9.16
