name: Periodically Build and Publish to Registry

env:
  IMAGE_ROOT: singleuser
  REGISTRY_HOSTNAME: docker.io
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}

on:
  schedule:
    - cron: '0 0 * * 0'  # At 00:00 every Sunday

  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 6
      # select a core set of images to build
      matrix:
        IMAGE_VARIANT:
          - base
          - scientific
          - r
          - summa
          - wrfhydro
          - csdms
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ github.event.action }} != 'workflow_dispatch'
      
      - name: Checkout, ref = ${{ github.ref_name }}
        uses: actions/checkout@v2
        if: ${{ github.event.action }} == 'workflow_dispatch'
        with:
          ref: ${{ github.ref_name }}

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ${{ env.IMAGE_ROOT }}
      
      - name: Docker Login
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin

      # Build the Docker image
      - name: Build
        run: |
          cd "${IMAGE_ROOT}"
          docker compose build ${{ matrix.IMAGE_VARIANT }}
      
      - name: Echo env configuration and set image tag
        id: tagging
        run: |
          echo "JH_BASE: ${{ env.JH_BASE }}"
          echo "CUAHSI_BASE: ${{ env.CUAHSI_BASE }}"
          echo "BUILD_DATE: ${{ env.BUILD_DATE }}"
          echo ------------
          export DOCKER_TAG="${REPOSITORY}/${IMAGE_ROOT}-${{ matrix.IMAGE_VARIANT }}:${{ env.CUAHSI_BASE }}"
          export DOCKER_FULL_PATH="$DOCKER_TAG-periodic-$(date +'%Y.%m.%d')"
          echo "DOCKER_FULL_PATH=$DOCKER_FULL_PATH" >> $GITHUB_ENV
          echo $DOCKER_FULL_PATH
          docker tag $DOCKER_TAG $DOCKER_FULL_PATH

      - name: Push Docker Image
        run: |
          docker push $DOCKER_FULL_PATH

    # TODO: run tests?
